#+title: Set up mu4e with mbsync
#+description: A guide on how to set up mu4e and mbsync

* Intro

Emacs can do /everything/. That includes managing mail. There are multiple mail programs for Eamcs, but I like to use mu4e.

** mbsync

You first need to set up mbsync to synchronize your mailbox. Install it with your package manager, then create a file called =.mbsyncrc= in your home directory.

#+begin_src sh
  IMAPAccount mcotocel
  Host imap.outlook.com
  User mcotocel@outlook.com
  PassCmd "gpg --quiet --for-your-eyes-only --no-tty --decrypt ~/.mbpassword.gpg"

  IMAPStore mcotocel-remote
  Account mcotocel

  MaildirStore mcotocel-local
  Path ~/Mail/mcotocel/
  Inbox ~/Mail/mcotocel/Inbox

  Channel mcotocel
  Master :mcotocel-remote:
  Slave :mcotocel-local:
  Patterns *
  Create Both
  SyncState *
#+end_src


Replace my name with your name. Then, create a file called =.mbpassword= and encrypt it with gpg. mbsync will automatically decrypt that file to read your password. When you're done, run the command =mbsync -a= to sync the mailbox.

** mu

Install =mu= from your package manager, then initialize it in the mail directory you set, and with the email address you set.

#+begin_src sh
  mu init --maildir=~/Mail --my-address=mcotocel@outlook.com
#+end_src

Then index it with the command =mu index=.

** mu4e

Mu4e is installed by default, so we just have to configure it.

#+begin_src emacs-lisp 
  (require 'mu4e)
  (setq mu4e-maildir (expand-file-name "~/Mail/"))

  (setq mu4e-drafts-folder "/Drafts")
  (setq mu4e-sent-folder   "/Sent")
  (setq mu4e-trash-folder  "/Deleted")

  (setq mu4e-get-mail-command "mbsync -a"
    mu4e-view-prefer-html t
    mu4e-update-interval 180
    mu4e-headers-auto-update t
    mu4e-compose-signature-auto-include nil
    mu4e-compose-format-flowed t)

  (setq
   user-mail-address "mcotocel@outlook.com"
   user-full-name  "Matei Cotocel")

  (setq mu4e-view-show-images t)

  (require 'org-mu4e)

  (setq org-mu4e-convert-to-html t)

  (setq message-send-mail-function 'smtpmail-send-it)
  (setq smtpmail-smtp-server "smtp-mail.outlook.com")
  (setq smtpmail-smtp-service 587 )
  (setq smtpmail-auth-credentials (expand-file-name "~/.authinfo"))
#+end_src

Replace the name and email address with your name and email address. Then, launch =mu4e=, sync the maildir, and you should be able to read, receive and send mail.
